use_frameworks!

platform :ios, '8.0'

target 'TQTool_test_Example' do
  pod 'TQTool_test', :path => '../'

  target 'TQTool_test_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
